###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

languageCode: en
title: "La Trobe Design System"

## Preprocessor settings
markdown: kramdown
kramdown:
  input: GFM

## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
sass:
    sass_dir: wedgetail/scss
exclude:
    - build.sh
    - server.sh

## Outputs the navigation collections
collections:
  docs:
    output: true
    permalink: /:path
  ltu-patterns:
    output: true


## Sets the default attributes for the Documentation and Pattern Files
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_docs/guidelines"
    values:
      type: guideline
  -
    scope:
      path: "_docs/getting-started"
    values:
      type: getting-started
  -
    scope:
      path: "_docs/components"
    values:
      type: component
  -
    scope:
      path: "_docs/foundations"
    values:
      type: foundation
  -
    scope:
      path: "_docs/elements"
    values:
      type: element
  -
    scope:
      path: "_docs/blocks"
    values:
      type: block
  -
    scope:
      path: "_docs/templates"
    values:
      type: template
  -
    scope:
      path: "_ltu-patterns/packages"
    values:
      status: draft
      layout: sample
  -
    scope:
      path: "_ltu-patterns/packages/blocks"
    values:
      layout: sample-block
  -
    scope:
      path: "_ltu-patterns/packages/templates"
    values:
      layout: sample-block
