###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

languageCode: en
title: "La Trobe Design System"

## Preprocessor settings
markdown: kramdown
kramdown:
  input: GFM

## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
sass:
    sass_dir: _sass

exclude:
    - build.sh
    - server.sh

## Outputs the navigation collections
collections:
  docs:
    output: true
    permalink: /:path
  ltu-components:
    output: true


## Sets the default attributes for the Documentation and Pattern Files
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "wedgetail"
  -
    scope:
      path: "_docs/guidelines"
    values:
      parentmenu: guideline
  -
    scope:
      path: "_docs/getting-started"
    values:
      parentmenu: getting-started
  -
    scope:
      path: "_docs/forms"
    values:
      parentmenu: form
  -
    scope:
      path: "_docs/content"
    values:
      parentmenu: 'content'
  -
    scope:
      path: "_docs/foundation"
    values:
      parentmenu: foundation
  -
    scope:
      path: "_docs/elements"
    values:
      parentmenu: element
  -
    scope:
      path: "_docs/navigation"
    values:
      parentmenu: navigation
  -
    scope:
      path: "_docs/examples"
    values:
      type: example
      parentmenu: example
  -
    scope:
      path: "_ltu-components/dist"
    values:
      layout: blank
  -
    scope:
      path: "_ltu-components/src"
    values:
      status: draft
      layout: snippet
  -
    scope:
      path: "_ltu-components/tests"
    values:
      type: example
      layout: snippet
