###################################
## General Settings

## These settings are standard Jekyll Settings, check the Jekyll docs for help

url: "https://latrobe-design-system.github.io"
languageCode: en
title: "La Trobe Design System"

## Preprocessor settings
markdown: kramdown
kramdown:
  input: GFM

## Generates Pattern Styles
## Disable to prevent pattern styles from being generated.
sass:
    sass_dir: ltu-patterns/assets/_sass
exclude:
    - build.sh
    - server.sh

## Outputs the navigation collections
collections:
  foundations: 
    output: true
  components:
    output: true
  elements:
    output: true
  blocks:
    output: true
  templates:
    output: true

## Sets the default attributes for the Documentation and Pattern Files
defaults:
    -
      scope:
        path: "" # an empty string here means all files in the project
      values:
        layout: "default"